# Generated by Django 4.0.2 on 2022-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
                ('tagline', models.CharField(max_length=150, verbose_name='Слоган курса')),
                ('amount_tasks', models.IntegerField(verbose_name='Интерактивных заданий')),
                ('video_time', models.IntegerField(verbose_name='Время видеоуроков')),
                ('portfolio', models.IntegerField(verbose_name='Работ в портфолио')),
                ('author', models.CharField(max_length=150, verbose_name='Работ в портфолио')),
                ('course_program', models.TextField(verbose_name='О курсе')),
                ('about_course_program', models.TextField(verbose_name='О курсе')),
                ('is_course_develop', models.PositiveSmallIntegerField(choices=[(1, 'Курс находится в разработке'), (2, 'Курс проходит проверку'), (3, 'Курс полностью готов'), (4, 'В курс вносятся правки')], default=1, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(max_length=1000, verbose_name='Ссылка на урок')),
                ('about_lesson_program', models.TextField(verbose_name='Информация об уроке')),
            ],
        ),
    ]
